AWSTemplateFormatVersion: '2010-09-09'

Description: Launch a basic EC2 instance in a specific VPC and subnet

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC for the instance

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Select a subnet for the instance

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Not secure in production, for demo only

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d03cb826412c6b0f # Amazon Linux 2 in ap-south-1
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: DemoInstance
